-- ============================================================================
-- HopeVisionAI - Insert Test Doctors for MVP
-- ============================================================================
-- Script pour insérer des médecins de test dans external_doctors
-- À exécuter dans Supabase SQL Editor pour tester le système de réservation
-- ============================================================================

-- Médecins de test (Tunisie)
INSERT INTO external_doctors (
    name,
    specialty,
    specialties,
    bio,
    phone,
    email,
    address,
    city,
    latitude,
    longitude,
    rating,
    total_reviews,
    consultation_price,
    teleconsultation_price,
    accepts_teleconsultation,
    certifications,
    languages,
    years_experience,
    is_verified,
    is_active,
    source
) VALUES
-- Médecin 1: Médecine Générale (Téléconsultation)
(
    'Dr Karim Ayari',
    'Médecine Générale',
    ARRAY['Médecine Générale', 'Médecine de famille'],
    'Médecin généraliste avec 15 ans d''expérience, spécialisé en médecine de famille et télémédecine.',
    '+216 71 123 456',
    'karim.ayari@example.com',
    '123 Avenue Habib Bourguiba',
    'Tunis',
    36.8065,
    10.1815,
    4.8,
    245,
    45.00,
    35.00,
    true,
    ARRAY['Télémédecine', 'HopeVisionAI'],
    ARRAY['Français', 'Arabe', 'Anglais'],
    15,
    true,
    true,
    'manual'
),
-- Médecin 2: Pneumologie (Spécialiste)
(
    'Dr Sarah Trabelsi',
    'Pneumologie',
    ARRAY['Pneumologie', 'Médecine respiratoire'],
    'Pneumologue certifiée, spécialisée dans les maladies respiratoires et les infections pulmonaires.',
    '+216 71 234 567',
    'sarah.trabelsi@example.com',
    '45 Rue de la République',
    'Tunis',
    36.8000,
    10.1700,
    4.9,
    312,
    65.00,
    50.00,
    true,
    ARRAY['Spécialiste', 'HopeVisionAI'],
    ARRAY['Français', 'Arabe'],
    12,
    true,
    true,
    'manual'
),
-- Médecin 3: Médecine Générale (Présentiel)
(
    'Dr Mohamed Gharbi',
    'Médecine Générale',
    ARRAY['Médecine Générale'],
    'Médecin généraliste expérimenté, consultations au cabinet uniquement.',
    '+216 71 345 678',
    'mohamed.gharbi@example.com',
    '78 Avenue de la Liberté',
    'Tunis',
    36.8100,
    10.1900,
    4.7,
    189,
    40.00,
    NULL,
    false,
    ARRAY['Télémédecine'],
    ARRAY['Français', 'Arabe'],
    20,
    true,
    true,
    'manual'
),
-- Médecin 4: Cardiologie
(
    'Dr Amira Ben Salah',
    'Cardiologie',
    ARRAY['Cardiologie', 'Médecine cardiovasculaire'],
    'Cardiologue spécialisée dans les maladies cardiovasculaires et la prévention.',
    '+216 71 456 789',
    'amira.bensalah@example.com',
    '12 Rue du Parc',
    'Tunis',
    36.8050,
    10.1750,
    4.9,
    428,
    70.00,
    55.00,
    true,
    ARRAY['Spécialiste', 'HopeVisionAI'],
    ARRAY['Français', 'Arabe', 'Anglais'],
    18,
    true,
    true,
    'manual'
),
-- Médecin 5: Dermatologie
(
    'Dr Youssef Mezzi',
    'Dermatologie',
    ARRAY['Dermatologie'],
    'Dermatologue spécialisé dans les maladies de la peau et les allergies cutanées.',
    '+216 71 567 890',
    'youssef.mezzi@example.com',
    '89 Boulevard du 9 Avril',
    'Tunis',
    36.8150,
    10.1850,
    4.6,
    156,
    55.00,
    45.00,
    true,
    ARRAY['Spécialiste'],
    ARRAY['Français', 'Arabe'],
    10,
    true,
    true,
    'manual'
),
-- Médecin 6: Pédiatrie
(
    'Dr Leila Khelifi',
    'Pédiatrie',
    ARRAY['Pédiatrie', 'Médecine infantile'],
    'Pédiatre spécialisée dans les soins aux enfants et adolescents.',
    '+216 71 678 901',
    'leila.khelifi@example.com',
    '34 Rue de la Médina',
    'Tunis',
    36.8000,
    10.1650,
    4.8,
    267,
    50.00,
    40.00,
    true,
    ARRAY['Spécialiste', 'HopeVisionAI'],
    ARRAY['Français', 'Arabe'],
    14,
    true,
    true,
    'manual'
),
-- Médecin 7: Gastro-entérologie
(
    'Dr Sami Bouazizi',
    'Gastro-entérologie',
    ARRAY['Gastro-entérologie'],
    'Gastro-entérologue spécialisé dans les maladies digestives.',
    '+216 71 789 012',
    'sami.bouazizi@example.com',
    '56 Avenue Mohamed V',
    'Tunis',
    36.8200,
    10.1800,
    4.7,
    198,
    60.00,
    50.00,
    true,
    ARRAY['Spécialiste'],
    ARRAY['Français', 'Arabe'],
    11,
    true,
    true,
    'manual'
),
-- Médecin 8: Neurologie
(
    'Dr Fatma Mansouri',
    'Neurologie',
    ARRAY['Neurologie'],
    'Neurologue spécialisée dans les maladies du système nerveux.',
    '+216 71 890 123',
    'fatma.mansouri@example.com',
    '23 Rue de Carthage',
    'Tunis',
    36.7950,
    10.1750,
    4.8,
    223,
    75.00,
    60.00,
    true,
    ARRAY['Spécialiste', 'HopeVisionAI'],
    ARRAY['Français', 'Arabe', 'Anglais'],
    16,
    true,
    true,
    'manual'
),
-- Médecin 9: Endocrinologie
(
    'Dr Tarek Jebali',
    'Endocrinologie',
    ARRAY['Endocrinologie', 'Diabétologie'],
    'Endocrinologue spécialisé dans le diabète et les troubles hormonaux.',
    '+216 71 901 234',
    'tarek.jebali@example.com',
    '67 Boulevard Bab Bhar',
    'Tunis',
    36.8050,
    10.1700,
    4.9,
    289,
    65.00,
    55.00,
    true,
    ARRAY['Spécialiste', 'HopeVisionAI'],
    ARRAY['Français', 'Arabe'],
    13,
    true,
    true,
    'manual'
),
-- Médecin 10: Médecine Générale (Sfax)
(
    'Dr Houda Fakhfakh',
    'Médecine Générale',
    ARRAY['Médecine Générale'],
    'Médecin généraliste à Sfax, consultations au cabinet et téléconsultation.',
    '+216 74 123 456',
    'houda.fakhfakh@example.com',
    '12 Avenue Hédi Chaker',
    'Sfax',
    34.7406,
    10.7603,
    4.7,
    178,
    42.00,
    35.00,
    true,
    ARRAY['Télémédecine'],
    ARRAY['Français', 'Arabe'],
    9,
    true,
    true,
    'manual'
)
ON CONFLICT (medin_id) DO NOTHING;

-- Vérifier l'insertion
SELECT 
    id,
    name,
    specialty,
    city,
    rating,
    consultation_price,
    accepts_teleconsultation,
    is_verified
FROM external_doctors
WHERE source = 'manual'
ORDER BY name;
