-- ============================================================================
-- Fix ALL Missing RLS INSERT Policies
-- ============================================================================
-- This fixes RLS errors for:
-- 1. AI Reports INSERT (generated by AI service)
-- 2. Diagnostic Hypotheses INSERT (linked to AI reports)
-- 3. Timeline Events INSERT (for AI analysis completion)
-- 4. Pre-analysis updates after image/document uploads
-- ============================================================================

-- ============================================================================
-- 1. AI REPORTS - INSERT POLICY
-- ============================================================================
-- Currently only SELECT policies exist, need INSERT policy
-- AI reports are created by the system when generating analysis

-- Drop existing INSERT policy if it exists (to avoid conflicts)
DROP POLICY IF EXISTS "System can create AI reports for patients" ON ai_reports;
DROP POLICY IF EXISTS "Patients can create own AI reports" ON ai_reports;

-- Create INSERT policy: Allow system to create AI reports for the patient's own pre-analyses
-- This is secure because it checks that the pre_analysis belongs to the patient
CREATE POLICY "System can create AI reports for patients"
    ON ai_reports FOR INSERT
    WITH CHECK (
        patient_profile_id IN (
            SELECT id FROM patient_profiles
            WHERE profile_id IN (
                SELECT id FROM profiles
                WHERE user_id = auth.uid()
                AND is_deleted = false
            )
        )
        AND pre_analysis_id IN (
            SELECT id FROM pre_analyses
            WHERE patient_profile_id IN (
                SELECT id FROM patient_profiles
                WHERE profile_id IN (
                    SELECT id FROM profiles
                    WHERE user_id = auth.uid()
                    AND is_deleted = false
                )
            )
        )
    );

-- ============================================================================
-- 2. DIAGNOSTIC HYPOTHESES - INSERT POLICY
-- ============================================================================
-- Currently only SELECT policies might exist, need INSERT policy

-- Drop existing INSERT policy if it exists
DROP POLICY IF EXISTS "System can create diagnostic hypotheses" ON diagnostic_hypotheses;
DROP POLICY IF EXISTS "Patients can create diagnostic hypotheses" ON diagnostic_hypotheses;

-- Create INSERT policy: Allow system to create hypotheses linked to AI reports owned by patient
CREATE POLICY "System can create diagnostic hypotheses"
    ON diagnostic_hypotheses FOR INSERT
    WITH CHECK (
        ai_report_id IN (
            SELECT id FROM ai_reports
            WHERE patient_profile_id IN (
                SELECT id FROM patient_profiles
                WHERE profile_id IN (
                    SELECT id FROM profiles
                    WHERE user_id = auth.uid()
                    AND is_deleted = false
                )
            )
        )
    );

-- ============================================================================
-- 3. TIMELINE EVENTS - INSERT POLICY
-- ============================================================================
-- Need to check if INSERT policy exists, if not create it

-- Drop existing INSERT policy if it exists
DROP POLICY IF EXISTS "Patients can create own timeline events" ON timeline_events;
DROP POLICY IF EXISTS "System can create timeline events for patients" ON timeline_events;

-- Create INSERT policy: Allow system/patients to create timeline events for their own profile
CREATE POLICY "Patients can create own timeline events"
    ON timeline_events FOR INSERT
    WITH CHECK (
        patient_profile_id IN (
            SELECT id FROM patient_profiles
            WHERE profile_id IN (
                SELECT id FROM profiles
                WHERE user_id = auth.uid()
                AND is_deleted = false
            )
        )
    );

-- ============================================================================
-- 4. VERIFY PRE_ANALYSES UPDATE POLICY
-- ============================================================================
-- Make sure the UPDATE policy allows updates even when pre_analysis doesn't exist yet
-- (This should already be fixed in supabase_fix_pre_analysis_rls_policies.sql, but verify)

-- The policy should allow updates without status restriction
-- Check if the new policy exists, if not create it
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'pre_analyses' 
        AND policyname = 'Patients can update own pre_analyses'
    ) THEN
        -- Create the policy
        CREATE POLICY "Patients can update own pre_analyses"
            ON pre_analyses FOR UPDATE
            USING (
                patient_profile_id IN (
                    SELECT id FROM patient_profiles
                    WHERE profile_id IN (
                        SELECT id FROM profiles
                        WHERE user_id = auth.uid()
                        AND is_deleted = false
                    )
                )
            )
            WITH CHECK (
                patient_profile_id IN (
                    SELECT id FROM patient_profiles
                    WHERE profile_id IN (
                        SELECT id FROM profiles
                        WHERE user_id = auth.uid()
                        AND is_deleted = false
                    )
                )
            );
    END IF;
END $$;

-- ============================================================================
-- 5. VERIFY DOCUMENTS INSERT POLICY
-- ============================================================================
-- Make sure documents can be inserted with correct patient_profile_id

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'documents' 
        AND policyname = 'Patients can create own documents'
    ) THEN
        CREATE POLICY "Patients can create own documents"
            ON documents FOR INSERT
            WITH CHECK (
                patient_profile_id IN (
                    SELECT id FROM patient_profiles
                    WHERE profile_id IN (
                        SELECT id FROM profiles
                        WHERE user_id = auth.uid()
                        AND is_deleted = false
                    )
                )
            );
    END IF;
END $$;

-- ============================================================================
-- 6. VERIFY PRE_ANALYSES INSERT POLICY
-- ============================================================================
-- Make sure pre_analyses can be inserted

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'pre_analyses' 
        AND policyname = 'Patients can create own pre_analyses'
    ) THEN
        CREATE POLICY "Patients can create own pre_analyses"
            ON pre_analyses FOR INSERT
            WITH CHECK (
                patient_profile_id IN (
                    SELECT id FROM patient_profiles
                    WHERE profile_id IN (
                        SELECT id FROM profiles
                        WHERE user_id = auth.uid()
                        AND is_deleted = false
                    )
                )
            );
    END IF;
END $$;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Run these to verify all policies exist:

-- SELECT tablename, policyname, cmd, qual, with_check 
-- FROM pg_policies 
-- WHERE tablename IN ('ai_reports', 'diagnostic_hypotheses', 'timeline_events', 'pre_analyses', 'documents')
-- ORDER BY tablename, policyname;

